export const APP_INIT_WEBSOCKET = 'APP_INIT_WEBSOCKET'
export const APP_CONNECTED_WEBSOCKET = 'APP_CONNECTED_WEBSOCKET';
export const APP_DISCONNECTED_WEBSOCKET = 'APP_DISCONNECTED_WEBSOCKET';
export const APP_HELP_COMMAND = 'APP_HELP_COMMAND';
export const APP_OPEN_COMMAND = 'APP_OPEN_COMMAND';
export const APP_START_COMMAND = 'APP_START_COMMAND';
